# Generated by Django 5.2.5 on 2025-08-30 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0001_initial'),
        ('Orders', '0002_orderitem_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Customers.customer'),
            preserve_default=False,
        ),
    ]
